In [4]:
import scipy.stats as stats


In [5]:
import seaborn as sns
import pandas as pd
import numpy as np
dataset=pd.read_csv('har.csv')

In [31]:
dataset.head()

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  tBodyAcc-std()-X  \
0           0.288585          -0.020294          -0.132905         -0.995279   
1           0.278419          -0.016411          -0.123520         -0.998245   
2           0.279653          -0.019467          -0.113462         -0.995380   
3           0.279174          -0.026201          -0.123283         -0.996091   
4           0.276629          -0.016570          -0.115362         -0.998139   

   tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyGyro-mean()-X  tBodyGyro-mean()-Y  \
0         -0.983111         -0.913526           -0.006101           -0.031365   
1         -0.975300         -0.960322           -0.016112           -0.083894   
2         -0.967187         -0.978944           -0.031698           -0.102335   
3         -0.983403         -0.990675           -0.043410           -0.091386   
4         -0.980817         -0.990482           -0.033960           -0.074708   

   tBodyGyro-mean()-Z  tBodyGyro-std()-X  tBodyGyro-std()-Y  \
0            0.107725          -0.985310          -0.976623   
1            0.100584          -0.983120          -0.989046   
2            0.096127          -0.976292          -0.993552   
3            0.085538          -0.991385          -0.992407   
4            0.077392          -0.985184          -0.992378   

   tBodyGyro-std()-Z  Activity  
0          -0.992205  STANDING  
1          -0.989121  STANDING  
2          -0.986379  STANDING  
3          -0.987554  STANDING  
4          -0.987402  STANDING

In [12]:
# Assuming you want to iterate over the first 5 indices
for i in range(5):  
    dataset_table = pd.crosstab(dataset['tBodyAcc-mean()-X'], dataset['tBodyAcc-mean()-Y'])
    print(dataset_table)

tBodyAcc-mean()-Y  -1.000000  -0.684893  -0.684097  -0.618098  -0.594207  \
tBodyAcc-mean()-X                                                          
-1.000000                  0          0          0          0          0   
-0.872395                  0          0          0          0          0   
-0.853848                  0          0          0          0          0   
-0.503823                  0          0          0          0          1   
-0.466440                  0          0          0          1          0   
...                      ...        ...        ...        ...        ...   
 0.631510                  0          0          0          0          0   
 0.632627                  0          0          0          0          0   
 0.680266                  0          0          0          0          0   
 0.692761                  0          0          0          0          0   
 1.000000                  0          0          0          0          0   

tBodyAcc-me

In [30]:
selected_features = ['tBodyAcc-mean()-X','tBodyAcc-mean()-Y','tBodyAcc-mean()-Z' ,'tBodyAcc-std()-X' , 'tBodyAcc-std()-Y' , 'tBodyAcc-std()-Z' , 'tBodyGyro-mean()-X' ,'tBodyGyro-mean()-Y','tBodyGyro-mean()-Z',
'tBodyGyro-std()-X',
'tBodyGyro-std()-Y',
'tBodyGyro-std()-Z' , 'Activity']

dataset = dataset[selected_features]

In [13]:
dataset_table.values 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
#Observed Values
Observed_Values = dataset_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
val=stats.chi2_contingency(dataset_table)

In [16]:
val

Chi2ContingencyResult(statistic=54007791.99999668, pvalue=0.23981482201978524, dof=54000446, expected_freq=array([[0.00013602, 0.00013602, 0.00013602, ..., 0.00013602, 0.00013602,
        0.00013602],
       [0.00013602, 0.00013602, 0.00013602, ..., 0.00013602, 0.00013602,
        0.00013602],
       [0.00013602, 0.00013602, 0.00013602, ..., 0.00013602, 0.00013602,
        0.00013602],
       ...,
       [0.00013602, 0.00013602, 0.00013602, ..., 0.00013602, 0.00013602,
        0.00013602],
       [0.00013602, 0.00013602, 0.00013602, ..., 0.00013602, 0.00013602,
        0.00013602],
       [0.00013602, 0.00013602, 0.00013602, ..., 0.00013602, 0.00013602,
        0.00013602]]))

In [17]:
Expected_Values=val[3]

In [18]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [19]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [20]:
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 14701.99999999832


In [21]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [22]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.0
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.0


In [23]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Reject H0,There is a relationship between 2 categorical variables
Reject H0,There is a relationship between 2 categorical variables


In [24]:
from scipy.stats import chi2_contingency

In [25]:

train_ds = pd.DataFrame(dataset)

results = []

for i in range(3):
    for j in range(i + 1, 3):
        contingency_table = pd.crosstab(train_ds.iloc[:, i], train_ds.iloc[:, j])
        chi2, p, _, _ = chi2_contingency(contingency_table)
        results.append({
            'Feature1': train_ds.columns[i],
            'Feature2': train_ds.columns[j],
            'Chi2 Statistic': chi2,
            'P-value': p
        })

results_df = pd.DataFrame(results)

print(results_df)

            Feature1           Feature2  Chi2 Statistic   P-value
0  tBodyAcc-mean()-X  tBodyAcc-mean()-Y    5.400779e+07  0.239815
1  tBodyAcc-mean()-X  tBodyAcc-mean()-Z    5.398574e+07  0.240309
2  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z    5.402250e+07  0.239785


In [32]:

train_ds = pd.DataFrame(dataset)

results = []

for i in range(3,6):
    for j in range(i+1,6):
        contingency_table = pd.crosstab(train_ds.iloc[:, i], train_ds.iloc[:, j])
        chi2, p, _, _ = chi2_contingency(contingency_table)

        results.append({
            'Feature1': train_ds.columns[i],
            'Feature2': train_ds.columns[j],
            'Chi2 Statistic': chi2,
            'P-value': p
        })

results_df = pd.DataFrame(results)
print(results_df)

           Feature1          Feature2  Chi2 Statistic   P-value
0  tBodyAcc-std()-X  tBodyAcc-std()-Y    5.401514e+07  0.239890
1  tBodyAcc-std()-X  tBodyAcc-std()-Z    5.400779e+07  0.239994
2  tBodyAcc-std()-Y  tBodyAcc-std()-Z    5.402250e+07  0.239845


In [33]:

train_ds = pd.DataFrame(dataset)

results = []

for i in range(6,9):
    for j in range(i+1,9):
        contingency_table = pd.crosstab(train_ds.iloc[:, i], train_ds.iloc[:, j])
        chi2, p, _, _ = chi2_contingency(contingency_table)

        results.append({
            'Feature1': train_ds.columns[i],
            'Feature2': train_ds.columns[j],
            'Chi2 Statistic': chi2,
            'P-value': p
        })

results_df = pd.DataFrame(results)
print(results_df)

             Feature1            Feature2  Chi2 Statistic   P-value
0  tBodyGyro-mean()-X  tBodyGyro-mean()-Y    5.404455e+07  0.239740
1  tBodyGyro-mean()-X  tBodyGyro-mean()-Z    5.403720e+07  0.239755
2  tBodyGyro-mean()-Y  tBodyGyro-mean()-Z    5.403720e+07  0.239755


In [34]:

train_ds = pd.DataFrame(dataset)

results = []

for i in range(9,12):
    for j in range(i+1,12):
        contingency_table = pd.crosstab(train_ds.iloc[:, i], train_ds.iloc[:, j])
        chi2, p, _, _ = chi2_contingency(contingency_table)

        results.append({
            'Feature1': train_ds.columns[i],
            'Feature2': train_ds.columns[j],
            'Chi2 Statistic': chi2,
            'P-value': p
        })

results_df = pd.DataFrame(results)
print(results_df)

            Feature1           Feature2  Chi2 Statistic   P-value
0  tBodyGyro-std()-X  tBodyGyro-std()-Y    5.400044e+07  0.239830
1  tBodyGyro-std()-X  tBodyGyro-std()-Z    5.399309e+07  0.240024
2  tBodyGyro-std()-Y  tBodyGyro-std()-Z    5.403720e+07  0.239755
